[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = 'colorscheme molokai'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
    let g:neoterm_default_mod='vertical'
    let g:neoterm_autoscroll=1
    tnoremap jj <c-\><c-n>
    nnoremap @c :Tnew<cr>
    nnoremap @e :T exit<cr>
    nnoremap rr :TREPLSendLine<cr><down>0
    vnoremap rr :<c-u>TREPLSendSelection<cr>:T<space>\<c<space><bs>r><cr>`>
    let s:venv_path = finddir("venv", ".;")
    if s:venv_path != ""
        let g:neoterm_repl_python = 'source ' . s:venv_path . '/bin/activate.fish; and ipython --no-autoindent'
    endif
'''
