[[plugins]]
repo = '~/.dein/repos/github.com/Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = 'colorscheme molokai'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
    let g:neoterm_default_mod='vertical'
    let g:neoterm_autoscroll=1
    tnoremap jj <c-\><c-n>
    nnoremap @c :Tnew<cr>
    nnoremap @e :T exit<cr>
    nnoremap rr :TREPLSendLine<cr><down>0
    nnoremap :: :T<space>
    vnoremap rr :<c-u>TREPLSendSelection<cr>:T<space>\<c<space><bs>r><cr>`>
    let s:venv_path = finddir("venv", ".;")
    if s:venv_path != ""
        let g:neoterm_repl_python = 'source ' . s:venv_path . '/bin/activate.fish; and ipython --no-autoindent'
    endif
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
    let g:neosnippet#disable_runtime_snippets={'_':1,}
    let g:neosnippet#snippets_directory='~/.config/nvim/snip'
    imap <expr><tab> neosnippet#expandable_or_jumpable() ? "\<plug>(neosnippet_expand_or_jump)" : "\<tab>"
    smap <expr><tab> neosnippet#expandable_or_jumpable() ? "\<plug>(neosnippet_expand_or_jump)" : "\<tab>"
    nnoremap @s :tabedit%<cr>:NeoSnippetEdit<cr>
    set completeopt-=preview
    "let g:neosnippet#enable_complete_done=1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
