version: "3"
services:
  websocket:
    image: ghcr.io/dr666m1/image_watcher_websocket
    volumes:
      - .:/work/sync
    ports:
      - "9999:9999"
  webserver:
    image: ghcr.io/dr666m1/image_watcher_webserver
    volumes:
      - .:/work/sync
    ports:
      - "8888:8888"
    depends_on:
      - websocket
